using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BossStatus : MonoBehaviour
{
    private enum BossState 
    {
        StartEnsyutu,  
        Battle,
        ClearEnsyutu,
    }

    private BossState nowState = BossState.StartEnsyutu;
    void Start()
    {
        
    }

    void Update()
    {
        switch (nowState)  
        {
            case BossState.StartEnsyutu:
                //“oê‰‰o‚Ìˆ—‚ğ‘‚­
                break;
            case BossState.Battle:
                //í“¬’†‚Ìˆ—‚ğ‘‚­
                break;
            case BossState.ClearEnsyutu:
                //ƒNƒŠƒA‚Ìˆ—‚ğ‘‚­
                break;
        }
    }
}